---
- name: Homework
  hosts: all 
  user: centos
  connection: ssh
  become: yes
  become_method: sudo
  tasks:
  vars_prompt:

  - name: username
    prompt: "What is your username?"
    private: no
  - name: Create SSH key for user jsmith in ~jsmith/.ssh/id_rsa
    user:
      name: bob
      generate_ssh_key: yes
      ssh_key_file: .ssh/id_rsa