---
- hosts: 18.217.248.146
  user: centos
  connection: ssh
  become: yes
  become_method: sudo
  tasks:
  - user:
      name: “{{item}}”
      state: present
      generate_ssh_key: true
    with_items:
    - bob
    - ben
    - lisa
    - katty
  - package:
      name: “{{item}}”
      state: present
    with_items:
    - httpd
    - php
    - epel-release
    - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    - php-mysql
    - mariadb
    - mariadb-server
    - MySQL-python
    - python-pip
    - wget
    - elinks
    - mysql
  - command: “yum-config-manager --enable remi-php74”
  - unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes
  - shell: “mv /var/www/html/wordpress/* /var/www/html”
    ignore_errors: true
  - command: “chown -R apache:apache /var/www/html”
  - shell: elinks://18.217.248.146
  - service:
      name: mariadb
      state: started
      enabled: true
  - selinux:
      policy: targeted
      state: permissive
  - service:
      name: “{{item}}”
      state: restarted
    with_items:
    - httpd
    - mariadb
  - script: “pip install boto”
    ignore_errors: yes
  - route53:
      state: create
      zone: maxirs.com
      record: wordpress.maxirs.com
      type: A
      ttl: 30
      value: 18.217.248.146
      wait: yes