---
- name: New Installation
  hosts: all
  user: centos
  connection: ssh
  become: yes
  become_method: sudo
  tasks:
  - name: Install Packages
    package:
      name: "{{item}}"
      state: present          #absent     latest
    with_items:
    - httpd 


  - name: Adds multiple users
    user:
      name: "{{item}}"
      state: present
    with_items:
    - bob
    - ben
    - lisa
    - katty